spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fintech_db_api?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
#    defer-datasource-initialization: true
#    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#  sql:
#    init:
#      mode: always